### ISSUE TITLE
Capybara::Mechanize::Node#click is broken on Ruby 3.0

### ISSUE THREAD

**Issue by tomstuart** [jeroenvandijk/capybara-mechanize#68]
Capybara DSL methods like `#click_link` work on Ruby 2.7 but fail on Ruby 3.0:

```
% gem info capybara capybara-mechanize

*** LOCAL GEMS ***

capybara (3.35.3)
    Authors: Thomas Walpole, Jonas Nicklas
    Homepage: https://github.com/teamcapybara/capybara
    License: MIT
    Installed at: /Users/tom/.gem/ruby/3.0.0

    Capybara aims to simplify the process of integration testing Rack
    applications, such as Rails, Sinatra or Merb

*** LOCAL GEMS ***

capybara-mechanize (1.11.0)
    Author: Jeroen van Dijk
    Homepage: https://github.com/jeroenvandijk/capybara-mechanize
    Installed at: /Users/tom/.gem/ruby/3.0.0

    RackTest driver for Capybara with remote request support

% ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]

% irb
>> require 'capybara/mechanize'
=> true
>> session = Capybara::Session.new(:mechanize, -> env { [200, {}, ['<a href="/bar">foo</a>']] })
=> #<Capybara::Session>
>> session.visit '/'
=> nil
>> session.click_link 'foo'
Traceback (most recent call last):
        ⋮
       11: from …/gems/capybara-3.35.3/lib/capybara/session.rb:762:in `click_link'
        ⋮
        4: from …/gems/capybara-mechanize-1.11.0/lib/capybara/mechanize/node.rb:12:in `click'
        3: from …/gems/capybara-3.35.3/lib/capybara/rack_test/node.rb:131:in `click'
        2: from …/gems/capybara-3.35.3/lib/capybara/rack_test/node.rb:131:in `call'
        1: from …/gems/capybara-3.35.3/lib/capybara/rack_test/node.rb:67:in `click'
ArgumentError (wrong number of arguments (given 2, expected 0..1))
```

I think this is because we’re [calling `super` with implicit arguments](https://github.com/jeroenvandijk/capybara-mechanize/blob/v1.11.0/lib/capybara/mechanize/node.rb#L12) in `Capybara::Mechanize::Node#click`. This calls `Capybara::RackTest::Node#click` [in the superclass](https://github.com/teamcapybara/capybara/blob/3.35.3/lib/capybara/rack_test/node.rb#L67) which accepts a single positional `keys` argument and `**options` keyword arguments. Ruby 3.0 has [stopped silently coercing](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) a final hash argument into keyword arguments, so the hash appears as a second positional argument and causes an `ArgumentError`:

```
% irb
>> class A
     def foo(x, **y); end
   end
=> :foo
>> class B < A
     def foo(x = [], y = {}); super; end
   end
=> :foo
>> B.new.foo
ArgumentError (wrong number of arguments (given 2, expected 1))
```

Superficially the solution would appear to be to change the second `Capybara::Mechanize::Node#click` argument from `offset = {}` to `**offset` (actually [`**options` now](https://github.com/teamcapybara/capybara/commit/2f2d82247156cfb8e169fe8e714bafdc6310f9fc#diff-51fea44755746b23ddd0a06cdb616bd340b8f9a866a40aaa72e28441f2624795R165)) so that it matches the signature of `#click` in the superclass, but I don’t know what the implications of that might be.

**Comment by puyo** [comment]
Also noticed this problem. `capybara-mechanize` seems pretty inactive. Any alternatives anyone happens to have found?

**Comment by phillbaker** [comment]
fixed in https://github.com/jeroenvandijk/capybara-mechanize/pull/69
